version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo "Build started on `date`"
  build:
    commands:
      - echo Running build process...
      - ./mvnw clean install -D skipTest
  post_build:
    commands:
      - echo "Build Completed on `date`"

artifacts:
  files:
    - '**/*'
